server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://mnsx.top:3306/mnsx_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  redis:
    host: mnsx.top
    port: 6379
    password: 123123
  rabbitmq:
    host: mnsx.top
    port: 5672
    username: root
    password: 123123
    virtual-host: center
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

oss:
  endpoint: oss-cn-hangzhou.aliyuncs.com
  accessKeyId: LTAI5tMQ5JPC5aVJzVgWuNv2
  accessKeySecret: dPHzgHXcqkBi6CPEhrINxdBX9mHRBI
  bucketName: mnsx-blog